In [1]:
import torch

In [2]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [3]:
x.numel()

12

In [5]:
x.reshape((3,-1))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [6]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.randn(3, 4)

tensor([[-0.4425,  0.2159,  0.1330,  1.2363],
        [-0.0675,  0.7419,  1.2857,  1.1368],
        [-1.2920, -0.5723, -0.8809,  0.8524]])

In [9]:
torch.tensor([[1, 2], [3, 4]])

tensor([[1, 2],
        [3, 4]])

In [10]:
x = x.reshape((3, -1))

In [12]:
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [13]:
x[-1]

tensor([ 8.,  9., 10., 11.])

In [15]:
x[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [17]:
x =torch.arange(12, dtype=torch.float32)

In [18]:
torch.exp(x)

tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
        4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04])

In [23]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
x+y, x-y, x*y, x/y, x**y

(tensor([4, 6]),
 tensor([-2, -2]),
 tensor([3, 8]),
 tensor([0.3333, 0.5000]),
 tensor([ 1, 16]))

In [30]:
x = torch.arange(12, dtype=torch.float32).reshape((3, -1))
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
x.shape, y.shape, torch.cat((x,y), dim=0), torch.cat((x,y), dim=1)

(torch.Size([3, 4]),
 torch.Size([3, 4]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [32]:
x==y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [33]:
x.sum()

tensor(66.)

Broadcasting

In [35]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [38]:
# a and b are respectively replicated along cols and rows
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

Saving memory

In [40]:
before = id(y)
y = y + x
id(y) == before

False

In [44]:
z = torch.zeros_like(y)
print("id(z):", id(z))
z[:] = x+y
print("id(z):", id(z))
z = x+y
print("id(z):", id(z))

id(z): 135197335001264
id(z): 135197335001264
id(z): 135193394146544


In [45]:
before = id(x)
x += y
id(x) == before

True

Conversion to objects

In [47]:
A = x.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [49]:
a = torch.Tensor([2.])
a, a.item(), float(a), int(a)

(tensor([2.]), 2.0, 2.0, 2)