In [3]:
import torch
import numpy as np

Derivatives and differentiation

In [2]:
def f(x):
    return 3 * x**2 - 4*x

In [12]:
for h in 10.**np.arange(-1, -6, -1):
    print(f"h={h:.5f}, f'(1)={(f(1+h)-f(1))/h}")

h=0.10000, f'(1)=2.3000000000000043
h=0.01000, f'(1)=2.0299999999999763
h=0.00100, f'(1)=2.002999999999311
h=0.00010, f'(1)=2.0002999999979565
h=0.00001, f'(1)=2.0000300000155846


Automatic differentiation

In [14]:
x = torch.arange(4.)
x

tensor([0., 1., 2., 3.])

In [16]:
print(x.grad)
x.requires_grad_(True)
print(x.grad)

None
None


In [19]:
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [20]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [21]:
x.grad == 4*x

tensor([True, True, True, True])

In [22]:
x.grad.zero_()
y = x.sum()
print(y)
y.backward()
x.grad

tensor(6., grad_fn=<SumBackward0>)


tensor([1., 1., 1., 1.])

In [25]:
x.grad.zero_()
y = x * x
print(y)
y.backward(gradient=torch.ones(len(y))) # faster: y.sum().backward()
x.grad

tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)


tensor([0., 2., 4., 6.])

In [26]:
x.grad.zero_()
y = x*x
print(y)
u = y.detach()
print(u)
z = u*x
print(z)
z.sum().backward()
x.grad==u

tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)
tensor([0., 1., 4., 9.])
tensor([ 0.,  1.,  8., 27.], grad_fn=<MulBackward0>)


tensor([True, True, True, True])