In [1]:
import os
os.listdir()

['main.ipynb', 'house_tiny.csv']

Reading data

In [2]:
fname = "house_tiny.csv"
with open(fname, 'w') as f:
    f.write('''NumRooms,RoofType,Price
NA,NA,127500
2,NA,106000
4,Slate,178100
NA,NA,140000''')

In [4]:
import pandas as pd
data = pd.read_csv("house_tiny.csv")
data

NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000

Data preparation

In [13]:
inputs, targets = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = pd.get_dummies(inputs, dummy_na=True)
inputs

NumRooms  RoofType_Slate  RoofType_nan
0       NaN           False          True
1       2.0           False          True
2       4.0            True         False
3       NaN           False          True

In [14]:
inputs = inputs.fillna(inputs.mean())
inputs

NumRooms  RoofType_Slate  RoofType_nan
0       3.0           False          True
1       2.0           False          True
2       4.0            True         False
3       3.0           False          True

In [15]:
import torch
X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(targets.to_numpy(dtype=float))
X, y

(tensor([[3., 0., 1.],
         [2., 0., 1.],
         [4., 1., 0.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

Reduction

In [16]:
X.sum()

tensor(16., dtype=torch.float64)

In [18]:
# keep numebr of dims
X.sum(dim=1, keepdim=True)

tensor([[4.],
        [3.],
        [5.],
        [4.]], dtype=torch.float64)

Dot products

In [22]:
y = torch.ones(3, dtype=torch.float32)
x = torch.arange(3, dtype=torch.float32)
x, y, torch.dot(x, y), torch.sum(x*y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.), tensor(3.))

Matrix-vector products

In [26]:
A = torch.randn(4, 3)
B = torch.ones(3, 4)
A, B


(tensor([[ 1.2347, -1.3598, -0.0447],
         [-0.5759,  0.1036, -0.1019],
         [-1.4540,  1.3463, -1.5866],
         [-0.3921,  0.2078, -1.0068]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [29]:
torch.mm(A, B), A@B

(tensor([[-0.1698, -0.1698, -0.1698, -0.1698],
         [-0.5743, -0.5743, -0.5743, -0.5743],
         [-1.6943, -1.6943, -1.6943, -1.6943],
         [-1.1911, -1.1911, -1.1911, -1.1911]]),
 tensor([[-0.1698, -0.1698, -0.1698, -0.1698],
         [-0.5743, -0.5743, -0.5743, -0.5743],
         [-1.6943, -1.6943, -1.6943, -1.6943],
         [-1.1911, -1.1911, -1.1911, -1.1911]]))

Norms

In [32]:
u = torch.tensor([3., -4.])
torch.norm(u), torch.abs(u).sum() # l2-norm and l1-norm

(tensor(5.), tensor(7.))